### ISSUE TITLE
HTTP Call Task results in error even though 200

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/community#225]
**Describe the bug**
The HTTP Call task results in an error on a 200 Get Request.

**To Reproduce**
I was testing this with a better uptime Heartbeat check

**Expected behavior**
200 response code means a successful task

**Additional context**
```
09/17/21 05:28:02 🔍  statusCode: 200
09/17/21 05:28:02 🔍  Setting individual task output parameter
09/17/21 05:28:02 🔍  Setting task output parameters
09/17/21 05:28:02 🔍  Resolving input parameter
09/17/21 05:28:02 🔍  Resolving input parameters...
09/17/21 05:28:02 🔍  Returning resolved parameters...
undefined:1
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/cli/commands/http.js:104:31)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Line 104 is `        const response = JSON.parse(output);` and I think its trying to parse an empty string of some kind.

**Comment by morarucostel** [comment]
@tlawrie You are spot on, its because of the empty response body.

I've pushed a PR35 - https://github.com/boomerang-io/worker.flow/pull/35 allowing now for the empty body to be considered valid.

**Comment by tlawrie** [comment]
Thanks @morarucostel

**Comment by tlawrie** [comment]
Closing as not planned: 2021 worker.flow bug; the tasks line has since been rewritten — reopen in boomerang-io/tasks if reproduced. Issues now live in boomerang-io/flow; reopen there if this still matters.
